# Generated by Django 5.2.3 on 2025-07-02 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=1200)),
                ('excerpt', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='blog/post')),
                ('author', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=64)),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
